server:
  port: 443 
  ssl:    enabled: true
    key-store: classpath:rateicecream.com.jks
    key-store-password: password
    key-store-type: JKS
#    key-alias: server
#    key-password: password
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:   url: jdbc:postgresql://revature-training.c8m2432hgexo.us-east-2.rds.amazonaws.com:5432/icecreamdb
   username: icecreamuser
   password: P@ssw0rd   driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  
        
   